#
# Deployment Specific configuration
#
# The following section is a template of the mandatory configuration that needs to be supplied in order to start the
# application, this config is deployment specific.
#
# Cloud Client API settings
#cloud:
#  client:
#    # Connection string to connect to the Cloud Client API
#    baseUri:
#
# Resource Server Configuration
#rs:
#  api:
#    # Connection string to the RS API base URI
#    uri:
#
# RCS Consent signing configuration
# See: com.forgerock.sapi.gateway.ob.uk.rcs.server.configuration.RcsApplicationConfiguration.rcsJwtSigner
#
#rcs:
#  consent:
#    response:
#      jwt:
#        # kid value to use in the header of JWS produced by this app
#        signingKeyId:
#        # path to the private key, this is expected to be a PEM file
#        privateKeyPath:
#        # iss value to specify in the claims of JWS produced by this app
#        issuer:
#        # Algo used to sign the JWS
#        signingAlgorithm: PS256
#

server:
  max-http-request-header-size: 16KB

logging:
  level:
    com.forgerock: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

# Configuration for API Provider information
# API provider is the organization that exposes the Open Banking API capabilities to be consumed by TPPs (usually a Bank)
# See: com.forgerock.sapi.gateway.ob.uk.rcs.server.configuration.ApiProviderConfiguration
api:
  provider:
    # Name used in ConsentDetails, this gets displayed in the Consent UI
    name: Test Bank

# Configuration for calling the Cloud Data repository
# com.forgerock.sapi.gateway.ob.uk.rcs.cloud.client.configuration.CloudClientConfiguration
cloud:
  client:
    api-client-path: /repo/apiclients/{apiClientId}
    users-path: /repo/users/{userId}


# RCS Consent Store config
consent:
  store:
    enabled:
      # Controls which intentTypes are supported
      intentTypes: ACCOUNT_ACCESS_CONSENT, PAYMENT_DOMESTIC_CONSENT, PAYMENT_DOMESTIC_SCHEDULED_CONSENT, PAYMENT_DOMESTIC_STANDING_ORDERS_CONSENT, DOMESTIC_VRP_PAYMENT_CONSENT, PAYMENT_FILE_CONSENT, CUSTOMER_INFO_CONSENT, PAYMENT_INTERNATIONAL_CONSENT, PAYMENT_INTERNATIONAL_SCHEDULED_CONSENT, PAYMENT_INTERNATIONAL_STANDING_ORDERS_CONSENT, FUNDS_CONFIRMATION_CONSENT

spring:
  data:
    mongodb:
      database: consent

# Configuration for calling the RS backoffice API
# See: com.forgerock.sapi.gateway.ob.uk.rcs.server.configuration.RsBackofficeConfiguration
rs:
  api:
    resource:
      customer-info:
        # Context endpoing to find customer information by userId
        findByUserId: /resources/customerinfo/findByUserId
    backoffice:
      uris:
        accounts:
          # Context endpoint to find accounts user by userId
          findUserById: /backoffice/accounts/search/findByUserId
          # Context endpoint to find account identifier by userId and account identifiers (name, identification and scheme name)
          findByAccountIdentifiers: /backoffice/accounts/search/findByAccountIdentifiers
        domestic-payments:
          # Context endpoint to find payment user by userId
          findUserById: /backoffice/domestic-payments/search/findByUserId
