---
apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.strategyType}}
    {{ if eq .Values.deployment.strategyType "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    {{ end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repo }}:{{ default .Chart.AppVersion .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.imagePullPolicy }}
          volumeMounts:
            - name: rcs-signing
              mountPath: /app/secrets
              readOnly: true
          ports:
            - name: http-server
              containerPort: {{ .Values.deployment.containerPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.deployment.containerPort }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          env:
          - name: SPRING_DATA_MONGODB_HOST
            value: {{ .Values.deployment.mongodb.host }}
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: ob-secrets
                key: MONGODB_CONSENT_USERNAME
          - name: SPRING_DATA_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ob-secrets
                key: MONGODB_CONSENT_USERNAME
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ob-secrets
                key: MONGODB_CONSENT_PASSWORD
          - name: CLOUD_CLIENT_BASE_URI
            valueFrom:
              configMapKeyRef:
                name: ob-deployment-config
                key: GATEWAY_DATA_REPO_URI
          - name: RS_API_URI
            valueFrom:
              configMapKeyRef:
                name: ob-deployment-config
                key: RS_API_URI
          - name: SERVER_PORT
            value: {{ .Values.deployment.containerPort | quote }}
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: JAVA_OPTS
            value: {{ .Values.deployment.java.opts }}
          - name: RCS_CONSENT_RESPONSE_JWT_PRIVATEKEYPATH
            value: /app/secrets/rcs-signing.key
          - name: RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID
            valueFrom:
              configMapKeyRef:
                name: ob-deployment-config
                key: RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID
          - name: RCS_CONSENT_RESPONSE_JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: ob-deployment-config
                key: RCS_CONSENT_RESPONSE_JWT_ISSUER
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      volumes:
        - name: rcs-signing
          secret:
            secretName: rcs-signing
            optional: false
