apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: {{ .Values.deployment.server.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}