deployment:
  apiVersion: apps/v1
  replicas: 1

  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 25%

  imagePullPolicy: Always

  # Deploy a different image to the intended release (useful for development)
  imageOverride:
    enabled: true
    repo: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-openbanking-uk-rcs
    tag: latest

  server:
    port: 8080

  cors:
    dnsRoot: localhost

  cdk:
    namespace: cdk
    am:
      hostname: am

  resources: {}

ingress:
  apiVersion: extensions/v1beta1
  class: nginx
  additionalAnnotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1m
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 100k

  domain: localhost
  subdomain: rcs
  tls:
    secretName: sslcert
    subdomain: "*"
  
service:
  apiVersion: v1
  type: ClusterIP
