# spring application

#Spring config
spring:
  cloud:
    config:
      uri: http://securebanking-config-server:8888
      failFast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
  application:
    name: securebanking-openbanking-uk-rcs
  profiles:
    active: NOT_SET

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

#Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Configuration properties entries for common libraries
common: # root key for all common 'securebanking-common-*' libraries
  cors: # library name
#    allowed_origins:
#      - "*"
#      - localhost
#      - forgerock.financial # valid for *.forgerock.financial
    allowed_headers: accept-api-version, x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, Id-Token
    allowed_methods: GET, PUT, POST, DELETE, OPTIONS, PATCH
    allowed_credentials: true # default value true
    max_age: 3600 # default value 3600
