name: merge-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: securebanking-openbanking-uk-rcs
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV
          echo "MAVEN_SERVER_ID=maven.forgerock.org-community" >> $GITHUB_ENV

      - name: Set Up Snapshot Forgerock Maven Repository
        if: contains( env.VERSION, 'SNAPSHOT')
        run: |
          echo "MAVEN_SERVER_ID=maven.forgerock.org-community-snapshots" >> $GITHUB_ENV

      # set java and cache
      - name: Set Java and Maven Cache
        uses: actions/setup-java@v4
        id: set_java_maven
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x64
          cache: 'maven'
          server-id: ${{ env.MAVEN_SERVER_ID }} # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: FR_ARTIFACTORY_USER # env variable for username in deploy
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable for token in deploy

      - name: Auth GCP 
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Build Changes
        run: |
          make verify
      
      - name: Deploy Artifact Package
        run: mvn -B deploy -DskipTests -DskipITs -DdockerCompose.skip -Ddockerfile.skip
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

      - name: Auth Docker 
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build Docker Image
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }}
          docker tag ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
          docker push ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }} --all-tags

  test:
    runs-on: ubuntu-latest
    name: Test Image
    needs: build
    steps:
      - name: 'Update Environment'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v ARGO_VALUES_PREFIX=remoteConsentServer -v SERVICE_NAME=remote-consent-server'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-rcs
        id: run-pipeline